// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Page  int32  `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	Count int32  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto1.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SearchResponse struct {
	Code int32                              `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Data []*SearchResponse_SearchResultItem `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto1.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SearchResponse) GetData() []*SearchResponse_SearchResultItem {
	if m != nil {
		return m.Data
	}
	return nil
}

type SearchResponse_SearchResultItem struct {
	Id     int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Detail string `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
}

func (m *SearchResponse_SearchResultItem) Reset()         { *m = SearchResponse_SearchResultItem{} }
func (m *SearchResponse_SearchResultItem) String() string { return proto1.CompactTextString(m) }
func (*SearchResponse_SearchResultItem) ProtoMessage()    {}
func (*SearchResponse_SearchResultItem) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

func (m *SearchResponse_SearchResultItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchResponse_SearchResultItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchResponse_SearchResultItem) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto1.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto1.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto1.RegisterType((*SearchResponse_SearchResultItem)(nil), "SearchResponse.SearchResultItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SearchService service

type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/SearchService/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SearchService service

type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}

func init() { proto1.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0xb4, 0x09, 0xca, 0xa1, 0x06, 0x74, 0x42, 0x28, 0xea, 0x14, 0x75, 0x0a, 0x4b,
	0x86, 0xc2, 0xc4, 0xc8, 0xc6, 0x04, 0x72, 0x37, 0x36, 0x13, 0x9f, 0xc0, 0x52, 0x5a, 0xa7, 0xce,
	0x19, 0xc1, 0x7f, 0xe2, 0x47, 0xa2, 0x9c, 0x5b, 0xa1, 0x76, 0xf2, 0x7d, 0xe7, 0xbb, 0xa7, 0x77,
	0x0f, 0x16, 0xf4, 0xad, 0xb7, 0x43, 0x4f, 0xed, 0xe0, 0x1d, 0xbb, 0xd5, 0x0b, 0x2c, 0x36, 0xa4,
	0x7d, 0xf7, 0xa9, 0x68, 0x1f, 0x68, 0x64, 0xbc, 0x81, 0x6c, 0x1f, 0xc8, 0xff, 0x54, 0x49, 0x9d,
	0x34, 0x85, 0x8a, 0x80, 0x08, 0xf3, 0x41, 0x7f, 0x50, 0x95, 0xd6, 0x49, 0x93, 0x29, 0xa9, 0xa7,
	0xc9, 0xce, 0x85, 0x1d, 0x57, 0x33, 0x69, 0x46, 0x58, 0xfd, 0x26, 0x50, 0x1e, 0x15, 0xc7, 0xc1,
	0xed, 0x46, 0x9a, 0x96, 0x3b, 0x67, 0x48, 0x14, 0x33, 0x25, 0x35, 0x3e, 0xc0, 0xdc, 0x68, 0xd6,
	0x55, 0x5a, 0xcf, 0x9a, 0xcb, 0x75, 0xdd, 0x9e, 0xae, 0xfc, 0x63, 0xe8, 0xf9, 0x99, 0x69, 0xab,
	0x64, 0x7a, 0xf9, 0x0a, 0xd7, 0xe7, 0x3f, 0x58, 0x42, 0x6a, 0xcd, 0x41, 0x3b, 0xb5, 0x66, 0xb2,
	0xc5, 0x96, 0xfb, 0xe8, 0xb5, 0x50, 0x11, 0xf0, 0x16, 0x72, 0x43, 0xac, 0x6d, 0x2f, 0x6e, 0x0b,
	0x75, 0xa0, 0xf5, 0xe3, 0xf1, 0xfe, 0x0d, 0xf9, 0x2f, 0xdb, 0x11, 0xde, 0x41, 0x1e, 0x1b, 0x58,
	0xb6, 0x27, 0xc9, 0x2c, 0xaf, 0xce, 0x4c, 0x3e, 0x5d, 0xbc, 0x65, 0x12, 0xe2, 0x7b, 0x2e, 0xcf,
	0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0x53, 0xe1, 0xd3, 0x5c, 0x01, 0x00, 0x00,
}
